export { default as Login} from './Auth/Login.jsx'
export { default as Logout} from './Auth/Logout.jsx'
export { default as Users} from './Users/Users.jsx'
export { default as Products} from './Products/Products.jsx'
export { default as Home} from './Home/Home.jsx'
export { default as WriteNewsletter} from './WriteNewsletter/WriteNewsletter.jsx'
export { default as Notifications} from './Notifications/Notifications.jsx'
export { default as Contacts} from './Contacts.jsx'

export { default as NotFound} from './NotFound.jsx'
